services: 
    # redis
    redis:
        image: redis:7.0.11-alpine

    # django
    django:
      container_name: django
      build: 
        context: .
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/usr/src/app/
      environment:
        - DEBUG=1
        - SECRET_KEY=JDSLDSOIOIODSIOOWEIDSJ;L;AJLDK
        - ALLOWED_HOSTS=localhost, 127.0.0.1
      depends_on:
        - redis


    # celery
    celery:
      container_name: celery
      build:
        context: .
      command: celery --app=dcelery worker -l INFO
      volumes:
        - .:/usr/src/app/
      environment:
        - DEBUG=1
        - SECRET_KEY=JDSLDSOIOIODSIOOWEIDSJ;L;AJLDK
        - ALLOWED_HOSTS=localhost, 127.0.0.1
      depends_on:
        - redis

